from skal.settings.common import *

SECRET_KEY = 'CHANGE_THIS'
SECURITY_PASSWORD_SALT = 'SOME_SALT'

RECAPTCHA_PUBLIC_KEY = '6Lcan7IUAAAAACXrZazA4OeWJ2ZAC1DdxgNK8wUX'
RECAPTCHA_PRIVATE_KEY = '6Lcan7IUAAAAANSmBbECrHlpz5EzSqNVX4uDiwH4'

#SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:password@localhost:5432/flask-beers-dev-db-1'
SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')

DEBUG = True
FLASK_DEBUG = True