"""empty message

Revision ID: 08354b678d4c
Revises: 0acfe42f411f
Create Date: 2020-10-09 20:36:36.378844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08354b678d4c'
down_revision = '0acfe42f411f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernight', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beernight', 'category')
    # ### end Alembic commands ###
