"""empty message

Revision ID: 0acfe42f411f
Revises: d20ffc369c37
Create Date: 2020-10-08 02:32:58.268692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acfe42f411f'
down_revision = 'd20ffc369c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernight', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beernight', 'is_featured')
    # ### end Alembic commands ###
