"""empty message

Revision ID: 14f5c0288839
Revises: 20597c3f9454
Create Date: 2020-10-13 00:16:29.087727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f5c0288839'
down_revision = '20597c3f9454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernight', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beernight', 'image_path')
    # ### end Alembic commands ###
