"""empty message

Revision ID: 20597c3f9454
Revises: 26fb4afbdfeb
Create Date: 2020-10-11 22:53:08.329219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20597c3f9454'
down_revision = '26fb4afbdfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('product_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'product_id')
    # ### end Alembic commands ###
