"""empty message

Revision ID: 21ab93204e78
Revises: 381969d569ed
Create Date: 2020-11-21 16:00:19.293058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ab93204e78'
down_revision = '381969d569ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'alcohol_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('alcohol_test', sa.REAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
