"""empty message

Revision ID: 26fb4afbdfeb
Revises: 08354b678d4c
Create Date: 2020-10-10 01:28:28.628213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fb4afbdfeb'
down_revision = '08354b678d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernight', sa.Column('copy_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beernight', 'copy_count')
    # ### end Alembic commands ###
