"""empty message

Revision ID: 337c611601b4
Revises: 8b2f0aad1796
Create Date: 2020-11-21 15:36:50.186139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337c611601b4'
down_revision = '8b2f0aad1796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('alcohol_num', sa.Float(precision=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'alcohol_num')
    # ### end Alembic commands ###
