"""empty message

Revision ID: 357a385d9636
Revises: fee5e556d11c
Create Date: 2020-10-18 13:00:24.260396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357a385d9636'
down_revision = 'fee5e556d11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beer', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('beernightBeer', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('beernightBeer', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('beer', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
