"""empty message

Revision ID: 381969d569ed
Revises: a9e98f84c829
Create Date: 2020-11-21 15:47:59.089002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381969d569ed'
down_revision = 'a9e98f84c829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('alcohol', sa.Float(precision=1), nullable=True))
    op.drop_column('beer', 'alcohol_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('alcohol_num', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('beer', 'alcohol')
    # ### end Alembic commands ###
