"""empty message

Revision ID: 435fff29891b
Revises: b899b0ca1f8e
Create Date: 2020-09-22 21:05:30.308477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435fff29891b'
down_revision = 'b899b0ca1f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_beernight',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('beernight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beernight_id'], ['beernight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('beernightbeerRating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('beernight_beer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beernight_beer_id'], ['beernightBeer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beernight_beer_id', 'user_id')
    )
    op.add_column('beernight', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('beernightRating', sa.Column('beernight_id', sa.Integer(), nullable=True))
    op.drop_constraint('beernightRating_beernight_beer_id_user_id_key', 'beernightRating', type_='unique')
    op.create_unique_constraint(None, 'beernightRating', ['beernight_id', 'user_id'])
    op.drop_constraint('beernightRating_beernight_beer_id_fkey', 'beernightRating', type_='foreignkey')
    op.create_foreign_key(None, 'beernightRating', 'beernight', ['beernight_id'], ['id'])
    op.drop_column('beernightRating', 'beernight_beer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernightRating', sa.Column('beernight_beer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'beernightRating', type_='foreignkey')
    op.create_foreign_key('beernightRating_beernight_beer_id_fkey', 'beernightRating', 'beernightBeer', ['beernight_beer_id'], ['id'])
    op.drop_constraint(None, 'beernightRating', type_='unique')
    op.create_unique_constraint('beernightRating_beernight_beer_id_user_id_key', 'beernightRating', ['beernight_beer_id', 'user_id'])
    op.drop_column('beernightRating', 'beernight_id')
    op.drop_column('beernight', 'is_public')
    op.drop_table('beernightbeerRating')
    op.drop_table('user_beernight')
    # ### end Alembic commands ###
