"""empty message

Revision ID: 4a88a4bd53be
Revises: 435fff29891b
Create Date: 2020-09-22 23:41:50.287956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a88a4bd53be'
down_revision = '435fff29891b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beernightbeerComment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('beer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beer_id'], ['beernightBeer.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['beernightbeerComment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('beernightbeerRating', sa.Column('beer_id', sa.Integer(), nullable=True))
    op.drop_constraint('beernightbeerRating_beernight_beer_id_user_id_key', 'beernightbeerRating', type_='unique')
    op.create_unique_constraint(None, 'beernightbeerRating', ['beer_id', 'user_id'])
    op.drop_constraint('beernightbeerRating_beernight_beer_id_fkey', 'beernightbeerRating', type_='foreignkey')
    op.create_foreign_key(None, 'beernightbeerRating', 'beernightBeer', ['beer_id'], ['id'])
    op.drop_column('beernightbeerRating', 'beernight_beer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernightbeerRating', sa.Column('beernight_beer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'beernightbeerRating', type_='foreignkey')
    op.create_foreign_key('beernightbeerRating_beernight_beer_id_fkey', 'beernightbeerRating', 'beernightBeer', ['beernight_beer_id'], ['id'])
    op.drop_constraint(None, 'beernightbeerRating', type_='unique')
    op.create_unique_constraint('beernightbeerRating_beernight_beer_id_user_id_key', 'beernightbeerRating', ['beernight_beer_id', 'user_id'])
    op.drop_column('beernightbeerRating', 'beer_id')
    op.drop_table('beernightbeerComment')
    # ### end Alembic commands ###
