"""empty message

Revision ID: 536127bfe402
Revises: e2b4774e3b81
Create Date: 2020-09-26 21:45:33.877377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536127bfe402'
down_revision = 'e2b4774e3b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'beernightinvitation', ['beernight_id', 'receiver_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'beernightinvitation', type_='unique')
    # ### end Alembic commands ###
