"""empty message

Revision ID: 566801971b7b
Revises: 536127bfe402
Create Date: 2020-09-30 02:06:49.691024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566801971b7b'
down_revision = '536127bfe402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('book_score', sa.Float(), nullable=True))
    op.add_column('beer', sa.Column('economic_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'economic_score')
    op.drop_column('beer', 'book_score')
    # ### end Alembic commands ###
