"""empty message

Revision ID: 5f2fd7e480c4
Revises: fe7283377ffd
Create Date: 2020-09-17 00:38:47.369256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2fd7e480c4'
down_revision = 'fe7283377ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beerComment', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.add_column('beerComment', sa.Column('text', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'beerComment', 'beerComment', ['parent_comment_id'], ['id'])
    op.drop_column('beerComment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beerComment', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'beerComment', type_='foreignkey')
    op.drop_column('beerComment', 'text')
    op.drop_column('beerComment', 'parent_comment_id')
    # ### end Alembic commands ###
