"""empty message

Revision ID: 65ec12c87c52
Revises: cf530f85d76e
Create Date: 2020-10-13 22:41:05.157591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ec12c87c52'
down_revision = 'cf530f85d76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'link_to_img')
    op.add_column('beernightBeer', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('beernightBeer', 'link_to_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernightBeer', sa.Column('link_to_img', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('beernightBeer', 'image_path')
    op.add_column('beer', sa.Column('link_to_img', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
