"""empty message

Revision ID: 68aefb86b6c0
Revises: 65ec12c87c52
Create Date: 2020-10-14 21:58:45.052090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aefb86b6c0'
down_revision = '65ec12c87c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('beer', sa.Column('drink_detail', sa.String(length=255), nullable=True))
    op.add_column('beer', sa.Column('vinbud_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'vinbud_link')
    op.drop_column('beer', 'drink_detail')
    op.drop_column('beer', 'category')
    # ### end Alembic commands ###
