"""empty message

Revision ID: 7e62ccd5e261
Revises: eb6d35c96ca5
Create Date: 2020-10-04 01:20:50.356620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e62ccd5e261'
down_revision = 'eb6d35c96ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernightBeer', sa.Column('alcohol', sa.Float(), nullable=True))
    op.add_column('beernightBeer', sa.Column('beer_type', sa.String(length=255), nullable=True))
    op.add_column('beernightBeer', sa.Column('book_score', sa.Float(), nullable=True))
    op.add_column('beernightBeer', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('beernightBeer', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('beernightBeer', sa.Column('economic_score', sa.Float(), nullable=True))
    op.add_column('beernightBeer', sa.Column('is_custom_made', sa.Boolean(), nullable=True))
    op.add_column('beernightBeer', sa.Column('link_to_img', sa.String(length=200), nullable=True))
    op.add_column('beernightBeer', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    op.add_column('beernightBeer', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('beernightBeer', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('beernightBeer', sa.Column('product_number', sa.Integer(), nullable=True))
    op.add_column('beernightBeer', sa.Column('volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beernightBeer', 'volume')
    op.drop_column('beernightBeer', 'product_number')
    op.drop_column('beernightBeer', 'price')
    op.drop_column('beernightBeer', 'name')
    op.drop_column('beernightBeer', 'manufacturer')
    op.drop_column('beernightBeer', 'link_to_img')
    op.drop_column('beernightBeer', 'is_custom_made')
    op.drop_column('beernightBeer', 'economic_score')
    op.drop_column('beernightBeer', 'description')
    op.drop_column('beernightBeer', 'country')
    op.drop_column('beernightBeer', 'book_score')
    op.drop_column('beernightBeer', 'beer_type')
    op.drop_column('beernightBeer', 'alcohol')
    # ### end Alembic commands ###
