"""empty message

Revision ID: 8b2a6f49aa84
Revises: 7583d519c655
Create Date: 2020-09-16 15:36:23.838613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2a6f49aa84'
down_revision = '7583d519c655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('product_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'product_number')
    # ### end Alembic commands ###
