"""empty message

Revision ID: 8b2f0aad1796
Revises: 9aaef918ffa4
Create Date: 2020-10-18 13:54:15.504339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2f0aad1796'
down_revision = '9aaef918ffa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernightBeer', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('beernightBeer', sa.Column('drink_detail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beernightBeer', 'drink_detail')
    op.drop_column('beernightBeer', 'category')
    # ### end Alembic commands ###
