"""empty message

Revision ID: a9e98f84c829
Revises: 337c611601b4
Create Date: 2020-11-21 15:47:30.034567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e98f84c829'
down_revision = '337c611601b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('alcohol_test', sa.Float(precision=1), nullable=True))
    op.drop_column('beer', 'alcohol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('alcohol', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('beer', 'alcohol_test')
    # ### end Alembic commands ###
