"""empty message

Revision ID: b7b730d0b816
Revises: 16c18daf80e9
Create Date: 2020-09-24 23:58:59.671061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b730d0b816'
down_revision = '16c18daf80e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernightbeerRating', sa.Column('feel', sa.Integer(), nullable=True))
    op.add_column('beernightbeerRating', sa.Column('sight', sa.Integer(), nullable=True))
    op.add_column('beernightbeerRating', sa.Column('smell', sa.Integer(), nullable=True))
    op.add_column('beernightbeerRating', sa.Column('taste', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beernightbeerRating', 'taste')
    op.drop_column('beernightbeerRating', 'smell')
    op.drop_column('beernightbeerRating', 'sight')
    op.drop_column('beernightbeerRating', 'feel')
    # ### end Alembic commands ###
