"""empty message

Revision ID: b899b0ca1f8e
Revises: 5f2fd7e480c4
Create Date: 2020-09-18 01:53:40.869329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b899b0ca1f8e'
down_revision = '5f2fd7e480c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_beernight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_beernight',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beernight_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beernight_id'], ['beernight.id'], name='user_beernight_beernight_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_beernight_user_id_fkey')
    )
    # ### end Alembic commands ###
