"""empty message

Revision ID: cf530f85d76e
Revises: 14f5c0288839
Create Date: 2020-10-13 19:22:56.040411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf530f85d76e'
down_revision = '14f5c0288839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('beer', 'product_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('product_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('beer', 'image_path')
    # ### end Alembic commands ###
