"""empty message

Revision ID: d20ffc369c37
Revises: 7e62ccd5e261
Create Date: 2020-10-04 22:18:56.340519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20ffc369c37'
down_revision = '7e62ccd5e261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beernight', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'beernight', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'beernight', type_='foreignkey')
    op.drop_column('beernight', 'creator_id')
    # ### end Alembic commands ###
