"""empty message

Revision ID: eb6d35c96ca5
Revises: 566801971b7b
Create Date: 2020-10-04 00:13:35.001636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6d35c96ca5'
down_revision = '566801971b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('link_to_img', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'link_to_img')
    # ### end Alembic commands ###
